Repository wowba/Wikinity, pull requests merged in 2023-09, with the labels that each got.

#4 Test: PR Test용 커밋
  src/pages/LoginPage/Login.tsx
Labels: question

#6 Feat: 회원가입, 계정생성 페이지 컴포넌트 추가 및 라우터 등록
  src/App.tsx
  src/pages/LoginPage/CreateAccount.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/LoginPage/SignUp.tsx
  src/styled/Login.ts
Labels: enhancement

#8 Feat: 회원가입 기능 구현
  src/firebaseSDK.ts
  src/pages/LoginPage/CreateAccount.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/LoginPage/SignUp.tsx
  src/styled/LoginPage/CreateAccount.ts
  src/styled/LoginPage/Login.ts
  src/styled/LoginPage/SignUp.ts
Labels: enhancement

#12 Feat: 공지사항 상세페이지 기초구현
  src/App.tsx
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/types/NoticePage/NoticeList.types.ts
Labels: enhancement

#14 Fix: alert eslint 오류 수정
  src/pages/NoticePage/NoticeWrite.tsx
Labels: bug

#15 Style: 공지사항 상세페이지 css작성
  src/index.css
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
  src/styled/NoticePage/NoticeDetail.styles.ts
  src/styled/NoticePage/NoticeList.styles.ts
Labels: 🎨html&css

#18 Feat: 로그인 및 로그아웃 임시 추가
  package-lock.json
  package.json
  src/App.tsx
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/MainPage/Main.tsx
  src/pages/TestPage/Test.tsx
  src/recoil/atoms/userState.ts
Labels: ✨Feature, ⚙Setting

#19 Chore: 불필요한 파일 제거
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
Labels: Chore

#20 Feat: firebase storage 이미지업로드 구현
  src/firebaseSDK.ts
  src/pages/NoticePage/NoticeWrite.tsx
Labels: ✨Feature

#21 Feat: firestorage 이미지 불러오기
  .eslintrc.json
  public/index.html
  public/manifest.json
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
Labels: ✨Feature

#24 Bug: Router 태그 수정
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
Labels: 🐞BugFix

#25 Bug: Router 다시 수정...
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
Labels: 🐞BugFix

#26 Style: 로그인 페이지 CSS 추가
  src/assets/fonts/Fonts.css
  src/assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
  src/index.tsx
  src/pages/LoginPage/Login.tsx
  src/styled/LoginPage/Login.ts
Labels: 🎨html&css

#27 Chore: 프로젝트 세팅
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firestore.rules
  src/firebaseSDK.ts
Labels: Chore

#28 Style: SignUp 페이지 스타일링
  src/pages/LoginPage/SignUp.tsx
  src/styled/LoginPage/SignUp.ts
Labels: 🎨html&css

#30 Style: 회원가입 폼 스타일 추가
  src/pages/LoginPage/CreateAccount.tsx
  src/styled/LoginPage/CreateAccount.ts
Labels: 🎨html&css

#32 Feat: Nav Bar 컴포넌트 추가
  src/assets/fonts/Fonts.css
  src/assets/fonts/RobotoMono-VariableFont_wght.ttf
  src/assets/img/Calendar.svg
  src/assets/img/Profile.svg
  src/assets/img/Todo.svg
  src/components/NavBar.tsx
  src/components/PrivateRoute.tsx
  src/pages/MainPage/Main.tsx
  src/styled/Common/NavBar.ts
Labels: ✨Feature

#33 Style: index.css 작성
  src/index.css
  src/index.tsx
Labels: 🎨html&css

#34 Feat: 공지사항 수정하기
  src/pages/NoticePage/NoticeWrite.tsx
  src/styled/NoticePage/NoticeDetail.styles.ts
  src/styled/NoticePage/NoticeWrite.styles.ts
Labels: ✨Feature

#35 Refactor: 공지사항 리스트 & 공지사항 작성 페이지 리팩토링
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
  src/types/NoticePage/NoticeList.types.ts
  src/utils/NoticePage/FetchNoticeData.ts
Labels: 🔨Refactor

#36 Feat: 페이지네이션 구현
  .eslintrc.json
  src/components/NavBar.tsx
  src/components/NoticePage/Pagination.tsx
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
  src/index.css
  src/pages/NoticePage/NoticeList.tsx
  src/styled/NoticePage/NoticeList.styles.ts
  src/styled/NoticePage/Pagination.styles.ts
Labels: ✨Feature

#37 Feat: 공지 리스트페이지 검색 기능 구현
  src/pages/NoticePage/NoticeList.tsx
  src/styled/NoticePage/NoticeList.styles.ts
Labels: ✨Feature

#38 공지사항 삭제 기능구현, 검색기능 추가 구현
  .eslintrc.json
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
  src/styled/NoticePage/NoticeList.styles.ts
Labels: ✨Feature

#40 Feat: 임시 깃허브 로그인 기능 추가
  src/App.tsx
  src/pages/LoginPage/CreateAccount.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/LoginPage/SignUp.tsx
Labels: ✨Feature, 🐞BugFix, Chore

#42 Feat: Github 로그인 제거
  src/pages/LoginPage/Login.tsx
  src/pages/LoginPage/SignUp.tsx
Labels: 🐞BugFix

#43 Chore: 프로젝트 설정 변경 및 불필요한 폴더 삭제
  src/firebaseSDK.ts
  wikinity/.gitignore
  wikinity/README.md
  wikinity/package-lock.json
  wikinity/package.json
  wikinity/public/favicon.ico
  wikinity/public/index.html
  wikinity/public/logo192.png
  wikinity/public/logo512.png
  wikinity/public/manifest.json
  wikinity/public/robots.txt
  wikinity/src/App.css
  wikinity/src/App.test.tsx
  wikinity/src/App.tsx
  wikinity/src/index.css
  wikinity/src/index.tsx
  wikinity/src/logo.svg
  wikinity/src/react-app-env.d.ts
  wikinity/src/reportWebVitals.ts
  wikinity/src/setupTests.ts
  wikinity/tsconfig.json
Labels: 🐞BugFix, Chore

#44 Style: 로그인 페이지 스타일 변경
  src/pages/LoginPage/Login.tsx
  src/styled/LoginPage/Login.ts
Labels: 🎨html&css

#45 Feat: 상단 프로필 모달 추가
  src/assets/img/CloseButton.svg
  src/components/NavBar.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/MainPage/ProfileModal.tsx
  src/recoil/atoms/userState.ts
  src/styled/LoginPage/Login.ts
  src/styled/MainPage/ProfileModal.ts
Labels: ✨Feature

#47 Feat: 유저 프로필 수정기능 추가 및 user, login atom 분리
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/MainPage/Main.tsx
  src/pages/MainPage/ProfileModal.tsx
  src/recoil/atoms/loginState.ts
  src/recoil/atoms/userState.ts
Labels: ✨Feature

#48 Feat: 카테고리 별 링크 강조 추가
  src/components/NavBar.tsx
  src/styled/Common/NavBar.ts
Labels: ✨Feature

#49 Refactor: 반복문 내 태그에 key 추가
  src/components/NavBar.tsx
Labels: 🔨Refactor

#50 BugFix: 로그아웃 후 로그인 시 에러 발생 해결
  src/pages/LoginPage/Login.tsx
  src/pages/MainPage/Main.tsx
  src/styled/LoginPage/Login.ts
Labels: 🐞BugFix

#51 Style: 로그인 버튼 스타일 변경
  src/styled/LoginPage/Login.ts
Labels: 🎨html&css

#52 Feat: 페이지네이션 이동버튼 구현
  src/components/NoticePage/Pagination.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/styled/NoticePage/NoticeDetail.styles.ts
  src/styled/NoticePage/NoticeList.styles.ts
  src/styled/NoticePage/Pagination.styles.ts
Labels: ✨Feature

#53 Feat: 사용자 프로필 이미지 변경 기능 추가
  src/assets/img/Camera.svg
  src/assets/img/DefaultProfile.png
  src/pages/LoginPage/CreateAccount.tsx
  src/pages/LoginPage/Login.tsx
  src/pages/MainPage/ProfileModal.tsx
  src/styled/MainPage/ProfileModal.ts
Labels: ✨Feature

#54 BugFix: 빠진 필드 추가
  src/pages/LoginPage/CreateAccount.tsx
Labels: 🐞BugFix

#57 Refactor: 로그아웃 버튼 위치 프로필 창으로 변경
  src/pages/MainPage/Main.tsx
  src/pages/MainPage/ProfileModal.tsx
  src/styled/MainPage/ProfileModal.ts
Labels: 🔨Refactor

#58 Style: ProfileModal 스타일 추가
  src/pages/MainPage/ProfileModal.tsx
  src/styled/MainPage/ProfileModal.ts
Labels: 🎨html&css

#60 Chore: 불필요한 폴더 삭제
  README.md
  src/api/.gitkeep
Labels: 📃Docs, Chore

#62 fix : wiki page 스타일 변경
  src/styled/WikiPage/Container.tsx
Labels: 🎨html&css

#63 Feat: 메인페이지 캐러셀 구현
  package-lock.json
  package.json
  src/pages/MainPage/Carousel.tsx
  src/pages/MainPage/Main.tsx
  src/styled/MainPage/Carousel.styles.ts
  src/utils/NoticePage/getNoticesData.ts
Labels: ✨Feature

#64 Feat: 로그인 엔터 이벤트 추가
  src/pages/LoginPage/Login.tsx
Labels: ✨Feature

#65 Feat : Todo 모달 기능 구현
  src/components/NavBar.tsx
  src/pages/MainPage/TodoModal.tsx
  src/pages/WikiPage/Wiki.tsx
  src/pages/WikiPage/components/ContentListItem.tsx
  src/recoil/atoms/main/TodoAtom.ts
  src/styled/MainPage/CommuteModal.ts
  src/styled/MainPage/ProfileModal.ts
  src/styled/MainPage/TodoModal.ts
  src/styled/WikiPage/Button.tsx
  src/styled/WikiPage/Container.tsx
  src/styled/WikiPage/Text.tsx
Labels: ✨Feature

#68 Feat: 회원가입 임시 Validation 추가
  src/pages/LoginPage/CreateAccount.tsx
  src/pages/LoginPage/Login.tsx
  src/styled/LoginPage/CreateAccount.ts
Labels: ✨Feature

#69 Feat: 모달 한번에 한개만 화면에 표시
  src/components/NavBar.tsx
  src/pages/MainPage/modal/CommuteModal.tsx
  src/pages/MainPage/modal/ProfileModal.tsx
  src/pages/MainPage/modal/TodoModal.tsx
Labels: ✨Feature

#70 Style: 모달 버튼 호버시 포인터 추가
  src/styled/MainPage/ProfileModal.ts
Labels: 🎨html&css

#71 Style : WikiPage style 변경
  src/pages/WikiPage/Wiki.tsx
  src/styled/WikiPage/Button.tsx
  src/styled/WikiPage/Container.tsx
  src/styled/WikiPage/Input.tsx
  src/styled/WikiPage/Item.tsx
  src/styled/WikiPage/Text.tsx
Labels: 🎨html&css

#72 BugFix: 모달 닫기 버튼 수정
  src/pages/MainPage/modal/CommuteModal.tsx
  src/pages/MainPage/modal/TodoModal.tsx
Labels: 🐞BugFix

#73 Style : 모달 내부 포인터 추가
  src/styled/MainPage/CommuteModal.ts
  src/styled/MainPage/TodoModal.ts
Labels: 🎨html&css

#74 Refactor : 카테고리 널 값 체크
  src/pages/WikiPage/components/Category.tsx
Labels: 🔨Refactor

#75 Style : 모달 스타일 통일
  src/pages/MainPage/modal/CommuteModal.tsx
  src/pages/MainPage/modal/ProfileModal.tsx
  src/pages/MainPage/modal/TodoModal.tsx
  src/pages/WikiPage/components/Category.tsx
  src/styled/Common/Modal.ts
  src/styled/MainPage/CommuteModal.ts
  src/styled/MainPage/ProfileModal.ts
  src/styled/MainPage/TodoModal.ts
  src/styled/WikiPage/Button.tsx
Labels: 🎨html&css

#77 Feat: 로그인 실패시 애니메이션 추가
  src/pages/LoginPage/Login.tsx
  src/styled/LoginPage/Login.ts
  src/utils/sleep.ts
Labels: ✨Feature

#78 Feat: 글 수정, 삭제 비밀번호 확인 추가, Enter키 검색 구현
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
Labels: ✨Feature

#79 Style: 로그인 창 placeholder transition 적용
  src/styled/LoginPage/Login.ts
Labels: 🎨html&css

#80 Style: 회원가입 정보 미기입시 애니메이션 추가
  src/pages/LoginPage/CreateAccount.tsx
  src/styled/LoginPage/CreateAccount.ts
Labels: 🎨html&css

#81 Style: NavBar Wikinity 링크 수정
  src/components/NavBar.tsx
Labels: 🎨html&css

#82 Refactor: ProfileModal.ts 공통 버튼 스타일드 컴포넌트 추가
  src/pages/MainPage/modal/ProfileModal.tsx
  src/styled/MainPage/ProfileModal.ts
Labels: 🔨Refactor

#83 Style: 공지 리스트페이지, 상세페이지, 캐러셀 디자인 수정
  src/pages/MainPage/Carousel.tsx
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/styled/MainPage/Carousel.styles.ts
  src/styled/NoticePage/NoticeDetail.styles.ts
  src/styled/NoticePage/NoticeList.styles.ts
Labels: 🎨html&css

#84 Style: 다른 페이지와 공통 스타일 통일시키기
  src/pages/NoticePage/NoticeDetail.tsx
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
  src/styled/NoticePage/NoticeDetail.styles.ts
  src/styled/NoticePage/NoticeList.styles.ts
  src/styled/NoticePage/NoticeWrite.styles.ts
Labels: 🎨html&css

#85 Refactor: 불필요한 Async Await 제거
  src/pages/LoginPage/Login.tsx
Labels: 🔨Refactor

#86 Refactor: Profile Modal 불필요한 Async Await 제거
  src/pages/MainPage/modal/ProfileModal.tsx
Labels: 🔨Refactor

#87 Refactor: 검색, 글 등록, 수정 시 공백 제어
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
Labels: 🔨Refactor

#88 Style: 웹사이트 제목, favicon 추가
  public/favicon.ico
  public/index.html
Labels: 🎨html&css

#89 Refactor: 게시물 없을 때 페이지네이션 수정
  .eslintrc.json
  src/pages/NoticePage/NoticeList.tsx
  src/pages/NoticePage/NoticeWrite.tsx
Labels: 🔨Refactor

#95 Refactor: button disabled 속성 제거
  README.md
  src/pages/LoginPage/CreateAccount.tsx
Labels: 🔨Refactor

#96 DOCS: readme.md 수정
  README.md
Labels: 📃Docs
